
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - proxy.diomedet.com
  resources:
  - oauth2proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.diomedet.com
  resources:
  - oauth2proxies/finalizers
  verbs:
  - update
- apiGroups:
  - proxy.diomedet.com
  resources:
  - oauth2proxies/status
  verbs:
  - get
  - patch
  - update
